name = "christchurch-commute"
main = "src/worker.ts"
compatibility_date = "2026-09-27"
workers_dev = true
preview_urls = false

[secrets]
required = [ "METRO_API_KEY", "JOURNEY_CONFIG", "JOURNEY_SCHEDULE", "COMMUTE_TOKEN" ]
